### ISSUE TITLE
BUG: The game will not load

### ISSUE THREAD

**Issue by lumbar527** [Dungeons-of-Kathallion/Bane-Of-Wargs#65]
### Describe The Bug

When trying to run the game, there is an error when reading yaml files.

### To Reproduce

1. Choose "Play Game"
2. Choose "Play Vanilla"
3. See error.

### Expected Behavior

I expected the yaml files to load properly.

### Save File

N/A

### Log File

Error:
<img width="802" alt="Screen Shot 2024-02-29 at 6 35 22 AM" src="https://github.com/Dungeons-of-Kathallion/Bane-Of-Wargs/assets/125756761/8215f454-cc93-4612-8a2f-d8a3ae5afa65">
Today's log:
[2024-02-29.log](https://github.com/Dungeons-of-Kathallion/Bane-Of-Wargs/files/14448736/2024-02-29.log)

### Version

4d86c68153ec2344a9d6cd79228fa902822f9b2d

### Additional Context

~~I am running from command line.~~
This error occurrs in command line and in running a build.

**Comment by OcelotWalrus** [comment]
This errors mean an item definition isn't valid. This happens because I've forgotten to update some of the data/ stuff!

**Comment by OcelotWalrus** [comment]
You see, in the newer versions of Bane Of Wargs; to make running the from everywhere possible so that compiled source code works; all the game data isn't stored in the cloned repository or the executable (in the executable you only find the source code). All the game data is stored in a folder in your system user config directory, but to keep that data updated, you need to turn on the `auto update` preferences parameter.

It's planned in the future that the program will automatically detect if there's a newer version but not yet to this day.

**Comment by lumbar527** [comment]
> It's planned in the future that the program will automatically detect if there's a newer version but not yet to this day.

What if the version was defined in some file?

**Comment by OcelotWalrus** [comment]
> > It's planned in the future that the program will automatically detect if there's a newer version but not yet to this day.
> 
> What if the version was defined in some file?

That's what's I'm currently doing. Is your issue fixed?
